In [1]:

#! pip install prodimopy
import import_ipynb
import InputParameters as Input
import GeneralFunctions as GF
import FileWritingReading as FWR
import DiscModel as DM
import LossFunctions as LF
import DiscModelLossFunctions as DMLF
import PropagatedEnergies as PE
import PropagatedSpectra as PS
import InjectionSpectra as IS
import SecondaryElectronFlux as SEF
from scipy import integrate
from scipy.interpolate import interp1d
import numpy as np
import matplotlib.pyplot as plt

importing Jupyter notebook from InputParameters.ipynb
importing Jupyter notebook from GeneralFunctions.ipynb
importing Jupyter notebook from FileWritingReading.ipynb
importing Jupyter notebook from DiscModel.ipynb
importing Jupyter notebook from LossFunctions.ipynb
importing Jupyter notebook from DiscModelLossFunctions.ipynb
importing Jupyter notebook from PropagatedEnergies.ipynb
importing Jupyter notebook from PropagatedSpectra.ipynb
importing Jupyter notebook from InjectionSpectra.ipynb
importing Jupyter notebook from SecondaryElectronFlux.ipynb
importing Jupyter notebook from IonisationCrossSections.ipynb


In [2]:
#Fixed Parameters (to modify computation time)

Pitch_Angle_Sample_Size=Input.Pitch_Angle_Sample_Size 
E_array=Input.E_array
E_Interpolation_array=Input.E_Interpolation_array


# Disc Model and Radial position of propagation
DiscModelName=Input.DiscModelName #Name of the disc model in wich particles are injected
DiscModel=DM.readDiscModel(DiscModelName)
Radial_index=Input.Radial_index # Index of the radius in the disc model where the particles are injected
# Flare parameters
Tflare=Input.Tflare # Flare temperature
muthinj=Input.muthinj # Injection energy of the Non-thermal particles in units of the thermal energy
alpha= Input.alpha # Power law index of the Non-thermal particles flux
EcoE= Input.EcoE # Cutoff energy of the Non-thermal particles flux


READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/ProDiMo.out  ...


READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Species.out  ...


/Users/vbrunn/opt/anaconda3/envs/py310/lib/python3.10/site-packages/prodimopy/read.py:2751: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  data._radFields_cache=np.chararray(shape=(data.nx,data.nz,data.nlam),itemsize=13)
/Users/vbrunn/opt/anaconda3/envs/py310/lib/python3.10/site-packages/prodimopy/read.py:2752: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  data._nmol_cache=np.chararray((data.nx,data.nz,data.nspec),itemsize=13)
/Users/vbrunn/opt/anaconda3/envs/py310/lib/python3.10/site-packages/prodimopy/read.py:2753: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  data._heat_cache=np.chararray((data.nx,data.nz,data.nheat),itemsize=13)
/Users/vbrunn/o

READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/FlineEstimates.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Elements.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/dust_opac.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/dust_sigmaa.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/StarSpectrum.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/gas_cs.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/line_flux.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/SED.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/SEDana.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/image.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Parameter.out  ...
INFO: Reading time:  1.25 s
 


/Users/vbrunn/opt/anaconda3/envs/py310/lib/python3.10/site-packages/prodimopy/read.py:2331: DeprecationWarning: `trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.
  self._Lbols[self.__incidx]=np.trapz(self.fnuErg[mask],x=self.nu[mask])*-1.0
/Users/vbrunn/opt/anaconda3/envs/py310/lib/python3.10/site-packages/prodimopy/read.py:2337: DeprecationWarning: `trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.
  self._Tbols[self.__incidx]=1.25e-11*np.trapz((self.nu[mask]*self.fnuErg[mask]),x=self.nu[mask])/np.trapz(self.fnuErg[mask],x=self.nu[mask])


In [3]:
PS.Primary_Proton_Flux(E_array,Radial_index,DiscModelName,Tflare,muthinj,alpha,EcoE,E_Interpolation_array,Pitch_Angle_Sample_Size)



READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/ProDiMo.out  ...


READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Species.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/FlineEstimates.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Elements.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/dust_opac.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/dust_sigmaa.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/StarSpectrum.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/gas_cs.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/line_flux.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/SED.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/SEDana.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/image.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Parameter.out  ...
INFO: Reading time:  1.13 s
 
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/ProDiMo.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Species.out  ...
REA

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        2.74782008e-05, 1.37461653e-05, 6.66067390e-06],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        2.74782008e-05, 1.37461653e-05, 6.66067390e-06],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        2.74782008e-05, 1.37461653e-05, 6.66067390e-06],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [4]:
PS.Primary_Electron_Flux(E_array,Radial_index,DiscModelName,Tflare,muthinj,alpha,EcoE,E_Interpolation_array,Pitch_Angle_Sample_Size)



READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/ProDiMo.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Species.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/FlineEstimates.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Elements.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/dust_opac.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/dust_sigmaa.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/StarSpectrum.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/gas_cs.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/line_flux.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/SED.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/SEDana.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/image.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Parameter.out  ...
INFO: Reading time:  1.10 s
 
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/ProDiMo.out  ...
REA

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.20098153e-05, 1.58569383e-05, 7.61201040e-06],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.20098153e-05, 1.58569383e-05, 7.61201040e-06],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.20098153e-05, 1.58569383e-05, 7.61201040e-06],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [5]:
SEF.Secondary_Electron_Flux_Electron(E_array, DiscModelName,Tflare, Radial_index)

READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/ProDiMo.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Species.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/FlineEstimates.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Elements.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/dust_opac.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/dust_sigmaa.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/StarSpectrum.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/gas_cs.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/line_flux.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/SED.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/SEDana.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/image.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Parameter.out  ...
INFO: Reading time:  1.04 s
 
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/ProDiMo.out  ...
REA

array([[1.45776314e+08, 1.73085732e+08, 2.05494102e+08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.44894046e+08, 1.72038182e+08, 2.04250410e+08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.43942983e+08, 1.70908950e+08, 2.02909744e+08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [6]:
SEF.Secondary_Electron_Flux_Proton(E_array, DiscModelName,Tflare, Radial_index)

READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/ProDiMo.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Species.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/FlineEstimates.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Elements.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/dust_opac.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/dust_sigmaa.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/StarSpectrum.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/gas_cs.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/line_flux.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/SED.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/SEDana.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/image.out  ...
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/Parameter.out  ...
INFO: Reading time:  1.02 s
 
READ: Reading File:  ProDiMoModels/CIW98_XN_AH_CIK/ProDiMo.out  ...
REA

array([[9.15631265e+07, 1.08857690e+08, 1.29417800e+08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [9.10089655e+07, 1.08198859e+08, 1.28634534e+08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [9.04118205e+07, 1.07488924e+08, 1.27790512e+08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])